name: Build Plugins-Only Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5'  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate Daily Version String
        id: vars
        run: |
          DATE=$(date +'%Y%m%d')

          COUNT=$(git tag -l "${DATE}.*" | wc -l)

          NEXT_NUM=$((COUNT + 1))

          VERSION="${DATE}.$(printf "%02d" $NEXT_NUM)"

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          echo "Generated Daily Version: $VERSION"

      - name: Create Archive
        run: |
          tar -cJf plugins-dist.tar.xz moodle/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: plugins-dist.tar.xz
          tag_name: ${{ steps.vars.outputs.VERSION }}
          name: ${{ steps.vars.outputs.VERSION }}
          body: |
            ### 📦 Release Details

            - **Version:** `${{ steps.vars.outputs.VERSION }}`
            - **Full Changelog:** [View release.md](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/release.md)

          draft: false
          prerelease: false

      # Wait a few seconds so GitHub API fully registers release
      - name: Wait for GitHub API sync
        run: sleep 10

      - name: Delete old releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          KEEP=5

          echo "Fetching releases..."

          gh release list \
            --limit 100 \
            --exclude-drafts \
            --json tagName,createdAt \
            --jq 'sort_by(.createdAt) | reverse' \
            > releases.json

          total=$(jq length releases.json)

          echo "Total releases: $total"

          if [ "$total" -le "$KEEP" ]; then
            echo "Nothing to delete."
            exit 0
          fi

          echo "Releases to delete:"

          jq -r ".[$KEEP:][] | .tagName" releases.json

          jq -r ".[$KEEP:][] | .tagName" releases.json | while read tag; do
            echo "Deleting release: $tag"

            gh release delete "$tag" \
              --yes \
              --cleanup-tag
          done
          
